version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /opt/tomcat8/webapps
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
